flight:
  uri: http://localhost:5566/InfyGoBoot/flights/
spring:
    datasource:
      username: root
      password: 
      url: jdbc:mysql://localhost:3306/db_irs_booking?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
bookingribbon:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:4401,http://localhost:4402
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka
    
    
