flight:
  uri: http://localhost:5566/InfyGoBoot/flights/
spring:
    datasource:
      username: root
      password: 
      url: jdbc:mysql://localhost:3306/db_irs_booking?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
