eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
    datasource:
        username: root
        password: 
        url: jdbc:mysql://localhost:3306/db_irs_flight?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
