spring:
    datasource:
        username: root
        password: 
        url: jdbc:mysql://localhost:3306/db_irs_payment?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

