spring:
    datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/db_irs_user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
